# Generated by Django 6.1.2 on 2026-10-10 15:56

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='field',
            name='longitude',
        ),
        migrations.AddField(
            model_name='field',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='field',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326),
        ),
    ]
